enum EEmployeeListConsts {
  FETCH_EMPLOYEE_LIST_REQUEST = "FETCH_EMPLOYEE_LIST_REQUEST",
  FETCH_EMPLOYEE_LIST_SUCCESS = "FETCH_EMPLOYEE_LIST_SUCCESS",
  FETCH_EMPLOYEE_LIST_FAILURE = "FETCH_EMPLOYEE_LIST_FAILURE",
}

export default EEmployeeListConsts;
