enum EEmployeeDetailsConsts {
  FETCH_EMPLOYEE_REQUEST = "FETCH_EMPLOYEE_REQUEST",
  FETCH_EMPLOYEE_SUCCESS = "FETCH_EMPLOYEE_SUCCESS",
  FETCH_EMPLOYEE_FAILURE = "FETCH_EMPLOYEE_FAILURE",

  UPDATE_EMPLOYEE_REQUEST = "UPDATE_EMPLOYEE_REQUEST",
  UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS",
  UPDATE_EMPLOYEE_FAILURE = "UPDATE_EMPLOYEE_FAILURE",

  SET_EDIT_MODE = "SET_EDIT_MODE",
}
export default EEmployeeDetailsConsts;
